### PR TITLE
fix training isvalid

### LINKED ISSUE #149: fix training IsValid for new records
the validity should be determined by the `TrainingDate` (service probably needs a new method for that). happy to do it in a followup

_Originally posted by @t-young31 in https://github.com/ucl-arc-tre/portal/pull/116#discussion_r2182559746_

### PR DESCRIPTION
**Pull request by t-young31**
### Checklist

- n/a Documentation has been updated

### CODE REVIEW

File: web/src/components/people/AdminView.tsx [hunk 1]
```diff
@@ -127,7 +127,10 @@ export default function AdminView() {
               <td className={styles.trainingInfo} data-cy="training">
                 <div className={styles.trainingRecord}>
                   {person.training_record.training_records?.map((training: TrainingRecord) => (
-                    <div key={`${training.kind}-${training.completed_at}`} className={styles.training}>
+                    <div
+                      key={`${person.user.id}-${training.kind}-${training.completed_at}`}
```
Comment (t-young31) [inline web/src/components/people/AdminView.tsx:131]: I don't think this div key was unique enough(?)

Comment (jhughes982) [reply web/src/components/people/AdminView.tsx:131]: Your updated version looks more unique to me, so I'd go with that 👍

**Review by jhughes982 — APPROVED** [review]
Looks good.
