### PR TITLE
fix external users search

### LINKED ISSUE #599: User search not retrieving external users
When searching external users by either email or username (I think username = the user's home tenant UPN) on the /people page, no matches are found.

Maybe this is because the `FindUsernames` function in the entra controller is asking the UCL entra tenant to `Select: []string{"userPrincipalName"}`: and for external users, this is only returning the `john.doe_contoso.com#EXT#@yourtenant.onmicrosoft.com` UCL-tenant UPN, which doesn't give any matches for usernames in the portal database.

instead we probably want the user's home tenant UPN (this seems to be what the portal records as the "username" when they login in for first time), but not clear how we can get that from speaking to the UCL tenant.

### PR DESCRIPTION
**Pull request by t-young31**
## Resolves #599

- Queries the db before falling back to entra to find users with a case insensitive match
- _should_ fix the lookup of external users in prod
- Drive by: fixes some RBAC for users search

### Checklist

- n/a Documentation has been updated

### CODE REVIEW

File: web/src/pages/people/index.tsx [hunk 1]
```diff
@@ -77,7 +78,7 @@ export default function PeoplePage() {
     }
   };
 
-  if (!isAdmin && !isTreOpsStaff && !isIAO) {
+  if (!isAdmin && !isTreOpsStaff && !isIAO && !canSearch) {
```
Comment (acholyn) [inline web/src/pages/people/index.tsx]:
```suggestion
  if (!canSearch) {
```

File: web/src/pages/people/index.tsx [hunk 2]
```diff
@@ -130,7 +133,7 @@ export default function PeoplePage() {
         </Alert>
       )}
 
-      {!isAdmin && <Callout construction />}
+      {!canSearch && <Callout construction />}
```
Comment (acholyn) [inline web/src/pages/people/index.tsx]: if they're not able to search, they can't view the page so don't think this is necessary. I think those who CAN search should still see the construction message until we've tested functionality
```suggestion
      {canSearch && <Callout construction />}
```

Comment (t-young31) [reply web/src/pages/people/index.tsx]: > if they're not able to search, they can't view the page

erm, nope

> those who CAN search should still see the construction message

this is exactly the opposite of what it was

File: web/src/pages/people/index.tsx (hunk 1 above)
Comment (t-young31) [reply web/src/pages/people/index.tsx]: IAO's can't search but can invite externals, so would receive an incorrect 'you can't view this page' error

Comment (acholyn) [reply web/src/pages/people/index.tsx]:
```suggestion
  if ( !isIAO && !canSearch) {
```

then? The repetition of admin and TREops is unnecessary at least

File: web/src/pages/people/index.tsx (hunk 2 above)
Comment (acholyn) [reply web/src/pages/people/index.tsx]: > > if they're not able to search, they can't view the page
> 
> erm, nope
> 
yeah, misread for the IAO; thought they could search as well

> > those who CAN search should still see the construction message
> 
> this is exactly the opposite of what it was

have revised my stance, think people who can search should know it's not flawless (yet)

File: web/src/pages/people/index.tsx (hunk 1 above)
Comment (t-young31) [reply web/src/pages/people/index.tsx]:
```suggestion
  if (!isIAO && !canSearch) {
```

File: web/src/pages/people/index.tsx (hunk 2 above)
Comment (t-young31) [reply web/src/pages/people/index.tsx]: none of the other functionality is flawless, so
```suggestion
      <Callout construction />
```
?

Comment (acholyn) [reply web/src/pages/people/index.tsx]: touché
honestly maybe we should just have a persistent banner across the whole site 😆

**Review by acholyn — APPROVED** [review]

**Comment by t-young31** [comment]
did you want to/have time to look at this before I merge @jhughes982? it would be good to ship this into prod on Wednesday

**Comment by jhughes982** [comment]
Don't let me hold this up. I can look at the code changes after it's merged as tomorrow will be busy due to TI planning. Happy for you to merge this in 👍
