### PR TITLE
fix base role assignment

### LINKED ISSUE #214: Persisted users should always be assigned a base role
## Description

**As a** dev
**I want to** have all users be assigned a base role
**So that** they can login to the portal

### PR DESCRIPTION
**Pull request by t-young31**
## Resolves #214

Found earlier with @acholyn  – whoops

### Checklist

- n/a Documentation has been updated

### CODE REVIEW

File: internal/middleware/user.go [hunk 1]
```diff
@@ -47,34 +45,14 @@ func (u *UserSetter) setUser(ctx *gin.Context) {
...
-	result := u.db.Where("username = ?", username).
-		Attrs(types.User{
-			Username: username,
-			Model:    types.Model{CreatedAt: time.Now()},
-		}).
-		FirstOrCreate(&user)
-	if result.Error != nil {
-		return user, types.NewErrServerError(result.Error)
+	if hasRole, err := rbac.HasRole(user, rbac.Base); err != nil && !hasRole {
+		_, _ = rbac.AddRole(user, rbac.Base)
```
Comment (acholyn) [inline internal/middleware/user.go:55]: what situations are we expecting this to proc in? (since in PersistedUser if the user is created they should then be given base role)

Comment (t-young31) [reply internal/middleware/user.go:55]: in the case the user has already been added with the wrong function, then tries to log in 🤦🏼

**Review by acholyn — APPROVED** [review]
🙌 😌

File: internal/service/users/user.go [hunk 2]
```diff
@@ -54,6 +55,28 @@ func (s *Service) AllUsers() ([]openapi.UserData, error) {
...
+	if result.Error != nil {
+		return user, types.NewErrServerError(result.Error)
+	}
+	userWasCreated := result.RowsAffected > 0
+	if userWasCreated {
+		if _, err := rbac.AddRole(user, rbac.Base); err != nil {
+			return user, fmt.Errorf("failed assign user base role: %v", err)
+		}
+	}
+	return user, nil
```
Comment (acholyn) [inline internal/service/users/user.go:77]: can we also return userWasCreated so it can be used in other conditionals after 🙏
